/**
 * KB-317 commit 2: generates the alias-fix migration from
 * scripts/catalogAliasFixes.ts - the same list build-catalog-seed.ts applies
 * to catalog-seed.json, so the seed and the database can't drift apart
 * (scripts/catalogAliasFixes.test.ts compares the committed file to this
 * output, byte for byte).
 *
 * Usage: npx tsx scripts/build-alias-migration.ts > supabase/migrations/<timestamp>_kb317_alias_fixes.sql
 */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { KB317_ALIAS_FIXES, type CatalogAliasFix } from "./catalogAliasFixes.js";

const sql = (value: string) => `'${value.replace(/'/g, "''")}'`;

function fixSql(fix: CatalogAliasFix): string[] {
  const name = sql(fix.displayName);
  const out = [
    `  -- ${fix.displayName}: ${fix.why}`,
    `  select array_agg(id) into v_ids from base_products where display_name = ${name};`,
    `  if coalesce(array_length(v_ids, 1), 0) <> 1 then`,
    `    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', ${name}, coalesce(array_length(v_ids, 1), 0);`,
    `  end if;`,
  ];
  for (const alias of fix.remove ?? []) {
    const a = sql(alias);
    out.push(
      `  update base_products set aliases = aliases - ${a}::text where id = v_ids[1] and aliases ? ${a};`,
      `  update shop_products set aliases = aliases - ${a}::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? ${a};`,
    );
  }
  for (const alias of fix.add ?? []) {
    const a = sql(alias);
    out.push(
      `  update base_products set aliases = aliases || jsonb_build_array(${a}::text) where id = v_ids[1] and not aliases ? ${a};`,
      `  update shop_products set aliases = aliases || jsonb_build_array(${a}::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? ${a};`,
    );
  }
  if (fix.deactivate) {
    out.push(
      `  update base_products set is_active = false where id = v_ids[1] and is_active;`,
      `  update shop_products set is_active = false, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and is_active;`,
    );
  }
  return out;
}

export function buildAliasMigrationSql(fixes: readonly CatalogAliasFix[]): string {
  return [
    "-- KB-317 commit 2: the owner's catalog alias rulings (29 Sep 2026).",
    "-- GENERATED by scripts/build-alias-migration.ts from scripts/catalogAliasFixes.ts",
    "-- (the list build-catalog-seed.ts also applies) - do not hand-edit.",
    "--",
    "-- Layer 1 reads each shop's OWN Dexie copy of shop_products, made from",
    "-- base_products at onboarding - so this fixes base_products (new shops) AND",
    "-- every existing shop's base-copied rows (source = 'base', found through",
    "-- base_product_id, so a shop that renamed the product is still reached).",
    "-- updated_at = now() on each changed shop row, so the ordinary pull",
    "-- (sync.ts pullShopProducts) brings it to the device.",
    "--",
    "-- Each product must match EXACTLY one base_products row, or the whole",
    "-- migration aborts - never a silent zero-row update that leaves the old",
    "-- aliases in place. Alias by alias, never overwriting a list, so a",
    "-- shopkeeper's own aliases survive. Idempotent: re-running changes nothing.",
    "",
    "do $$",
    "declare",
    "  v_ids uuid[];",
    "begin",
    fixes.map((fix) => fixSql(fix).join("\n")).join("\n\n"),
    "end",
    "$$;",
    "",
  ].join("\n");
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.stdout.write(buildAliasMigrationSql(KB317_ALIAS_FIXES));
}
