/**
 * KB-108: generates the base_products seed migration's SQL from
 * src/domain/catalog-seed.json - the same file the domain layer itself is
 * built and tested against (via scripts/build-catalog-seed.ts).
 *
 * Deliberately not hand-authored: 482 rows typed by hand is exactly the
 * kind of transcription-error risk this project avoids everywhere else,
 * and generating from catalog-seed.json guarantees base_products and the
 * domain layer's own catalog can never drift apart - both trace back to
 * the one source file.
 *
 * Run once, its OUTPUT is what gets committed as an actual timestamped
 * migration file under supabase/migrations/ - this script itself is not
 * part of the migration and is not run at push/deploy time.
 *
 * Usage: npx tsx scripts/build-base-products-migration.ts > supabase/migrations/<timestamp>_seed_base_products.sql
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

interface CatalogEntry {
  id: string;
  displayName: string;
  sourceCategory: string;
  guardCategory: string;
  unit: string;
  suggestedPricePaise: number;
  aliases: string[];
  isActive: boolean;
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJsonbArray(values: string[]): string {
  return `'${JSON.stringify(values).replace(/'/g, "''")}'::jsonb`;
}

function main(): void {
  const seedPath = join(__dirname, "..", "src", "domain", "catalog-seed.json");
  const raw = readFileSync(seedPath, "utf8");
  const parsed = JSON.parse(raw) as CatalogEntry[] | { products: CatalogEntry[] };
  const products = Array.isArray(parsed) ? parsed : parsed.products;

  const seenNames = new Map<string, string>();
  for (const p of products) {
    const key = p.displayName.toLowerCase();
    const existing = seenNames.get(key);
    if (existing) {
      throw new Error(
        `Refusing to generate: duplicate display_name "${p.displayName}" (ids ${existing} and ${p.id}) ` +
          `would violate shop_products's unique (shop_id, lower(display_name)) index once copied into a ` +
          `shop. Fix at the source in scripts/build-catalog-seed.ts's PRODUCT_RUNTIME_FIXES, not here.`,
      );
    }
    seenNames.set(key, p.id);
  }

  const values = products
    .map((p) => {
      return (
        `  (gen_random_uuid(), 1, ${sqlString(p.displayName)}, ${sqlString(p.sourceCategory)}, ` +
        `${sqlString(p.guardCategory)}, ${sqlString(p.unit)}, ${p.suggestedPricePaise}, ` +
        `${sqlJsonbArray(p.aliases)}, ${p.isActive})`
      );
    })
    .join(",\n");

  const sql = `-- KB-108: seeds base_products from src/domain/catalog-seed.json.
-- GENERATED by scripts/build-base-products-migration.ts - do not hand-edit.
-- To regenerate: npx tsx scripts/build-base-products-migration.ts
--
-- catalog_version = 1: the first seed. A future catalog update inserts a
-- new version's rows rather than overwriting these, per
-- 03-DATA-MODEL.md's "versioned" framing - the update mechanism itself is
-- a later ticket's concern, not this one's.
--
-- Generation refuses to proceed if any two products share a display_name
-- (case-insensitive) - see KI-26 (docs/12-PARKED.md), fixed at the source
-- in scripts/build-catalog-seed.ts's PRODUCT_RUNTIME_FIXES before this
-- file was generated, not patched here.

insert into base_products (
  id, catalog_version, display_name, source_category, guard_category,
  default_unit, suggested_price_paise, aliases, is_active
)
values
${values};
`;

  process.stdout.write(sql);
}

main();
