-- KB-317 commit 2: the owner's catalog alias rulings (29 Sep 2026).
-- GENERATED by scripts/build-alias-migration.ts from scripts/catalogAliasFixes.ts
-- (the list build-catalog-seed.ts also applies) - do not hand-edit.
--
-- Layer 1 reads each shop's OWN Dexie copy of shop_products, made from
-- base_products at onboarding - so this fixes base_products (new shops) AND
-- every existing shop's base-copied rows (source = 'base', found through
-- base_product_id, so a shop that renamed the product is still reached).
-- updated_at = now() on each changed shop row, so the ordinary pull
-- (sync.ts pullShopProducts) brings it to the device.
--
-- Each product must match EXACTLY one base_products row, or the whole
-- migration aborts - never a silent zero-row update that leaves the old
-- aliases in place. Alias by alias, never overwriting a list, so a
-- shopkeeper's own aliases survive. Idempotent: re-running changes nothing.

do $$
declare
  v_ids uuid[];
begin
  -- गेहूं: आटा is flour (Chakki Aata), not grain
  select array_agg(id) into v_ids from base_products where display_name = 'गेहूं';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'गेहूं', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases - 'आटा'::text where id = v_ids[1] and aliases ? 'आटा';
  update shop_products set aliases = aliases - 'आटा'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'आटा';

  -- Chakki Aata: आटा = Chakki Aata (owner)
  select array_agg(id) into v_ids from base_products where display_name = 'Chakki Aata';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Chakki Aata', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases || jsonb_build_array('आटा'::text) where id = v_ids[1] and not aliases ? 'आटा';
  update shop_products set aliases = aliases || jsonb_build_array('आटा'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'आटा';

  -- Bath Sabun: a bare sabun is the generic Sabun, never Bath Sabun
  select array_agg(id) into v_ids from base_products where display_name = 'Bath Sabun';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Bath Sabun', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases - 'sabun'::text where id = v_ids[1] and aliases ? 'sabun';
  update shop_products set aliases = aliases - 'sabun'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'sabun';
  update base_products set aliases = aliases - 'साबुन'::text where id = v_ids[1] and aliases ? 'साबुन';
  update shop_products set aliases = aliases - 'साबुन'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'साबुन';

  -- Sabun: sabun = generic Sabun (614) (owner)
  select array_agg(id) into v_ids from base_products where display_name = 'Sabun';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Sabun', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases || jsonb_build_array('sabun'::text) where id = v_ids[1] and not aliases ? 'sabun';
  update shop_products set aliases = aliases || jsonb_build_array('sabun'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'sabun';
  update base_products set aliases = aliases || jsonb_build_array('साबुन'::text) where id = v_ids[1] and not aliases ? 'साबुन';
  update shop_products set aliases = aliases || jsonb_build_array('साबुन'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'साबुन';

  -- Desi Shakkar: bare shakkar = Chini (owner); Desi Shakkar only when desi is said
  select array_agg(id) into v_ids from base_products where display_name = 'Desi Shakkar';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Desi Shakkar', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases - 'shakkar'::text where id = v_ids[1] and aliases ? 'shakkar';
  update shop_products set aliases = aliases - 'shakkar'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'shakkar';

  -- Arhar Daal: toor = arhar, one pulse (owner): Toor Daal (16) only; Arhar Daal (Rs.140) deactivated
  select array_agg(id) into v_ids from base_products where display_name = 'Arhar Daal';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Arhar Daal', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases - 'arhar daal'::text where id = v_ids[1] and aliases ? 'arhar daal';
  update shop_products set aliases = aliases - 'arhar daal'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'arhar daal';
  update base_products set aliases = aliases - 'tur daal'::text where id = v_ids[1] and aliases ? 'tur daal';
  update shop_products set aliases = aliases - 'tur daal'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'tur daal';
  update base_products set aliases = aliases - 'tuvar dal'::text where id = v_ids[1] and aliases ? 'tuvar dal';
  update shop_products set aliases = aliases - 'tuvar dal'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'tuvar dal';
  update base_products set aliases = aliases - 'toor dal'::text where id = v_ids[1] and aliases ? 'toor dal';
  update shop_products set aliases = aliases - 'toor dal'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'toor dal';
  update base_products set aliases = aliases - 'pigeon pea'::text where id = v_ids[1] and aliases ? 'pigeon pea';
  update shop_products set aliases = aliases - 'pigeon pea'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'pigeon pea';
  update base_products set aliases = aliases - 'अरहर दाल'::text where id = v_ids[1] and aliases ? 'अरहर दाल';
  update shop_products set aliases = aliases - 'अरहर दाल'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'अरहर दाल';
  update base_products set aliases = aliases - 'तुअर दाल'::text where id = v_ids[1] and aliases ? 'तुअर दाल';
  update shop_products set aliases = aliases - 'तुअर दाल'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'तुअर दाल';
  update base_products set aliases = aliases - 'तूर दाल'::text where id = v_ids[1] and aliases ? 'तूर दाल';
  update shop_products set aliases = aliases - 'तूर दाल'::text, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and aliases ? 'तूर दाल';
  update base_products set is_active = false where id = v_ids[1] and is_active;
  update shop_products set is_active = false, updated_at = now() where base_product_id = v_ids[1] and source = 'base' and is_active;

  -- Toor Daal: toor = arhar (owner); तुवर दाल (owner's spelling list) and तूअल दाल (RT23, Whisper's ल for र) are below the fuzzy bar even after the folds
  select array_agg(id) into v_ids from base_products where display_name = 'Toor Daal';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Toor Daal', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases || jsonb_build_array('arhar'::text) where id = v_ids[1] and not aliases ? 'arhar';
  update shop_products set aliases = aliases || jsonb_build_array('arhar'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'arhar';
  update base_products set aliases = aliases || jsonb_build_array('arhar daal'::text) where id = v_ids[1] and not aliases ? 'arhar daal';
  update shop_products set aliases = aliases || jsonb_build_array('arhar daal'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'arhar daal';
  update base_products set aliases = aliases || jsonb_build_array('tur daal'::text) where id = v_ids[1] and not aliases ? 'tur daal';
  update shop_products set aliases = aliases || jsonb_build_array('tur daal'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'tur daal';
  update base_products set aliases = aliases || jsonb_build_array('tuvar dal'::text) where id = v_ids[1] and not aliases ? 'tuvar dal';
  update shop_products set aliases = aliases || jsonb_build_array('tuvar dal'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'tuvar dal';
  update base_products set aliases = aliases || jsonb_build_array('toor dal'::text) where id = v_ids[1] and not aliases ? 'toor dal';
  update shop_products set aliases = aliases || jsonb_build_array('toor dal'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'toor dal';
  update base_products set aliases = aliases || jsonb_build_array('pigeon pea'::text) where id = v_ids[1] and not aliases ? 'pigeon pea';
  update shop_products set aliases = aliases || jsonb_build_array('pigeon pea'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'pigeon pea';
  update base_products set aliases = aliases || jsonb_build_array('अरहर दाल'::text) where id = v_ids[1] and not aliases ? 'अरहर दाल';
  update shop_products set aliases = aliases || jsonb_build_array('अरहर दाल'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'अरहर दाल';
  update base_products set aliases = aliases || jsonb_build_array('तुअर दाल'::text) where id = v_ids[1] and not aliases ? 'तुअर दाल';
  update shop_products set aliases = aliases || jsonb_build_array('तुअर दाल'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'तुअर दाल';
  update base_products set aliases = aliases || jsonb_build_array('तूर दाल'::text) where id = v_ids[1] and not aliases ? 'तूर दाल';
  update shop_products set aliases = aliases || jsonb_build_array('तूर दाल'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'तूर दाल';
  update base_products set aliases = aliases || jsonb_build_array('तुवर दाल'::text) where id = v_ids[1] and not aliases ? 'तुवर दाल';
  update shop_products set aliases = aliases || jsonb_build_array('तुवर दाल'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'तुवर दाल';
  update base_products set aliases = aliases || jsonb_build_array('तूअल दाल'::text) where id = v_ids[1] and not aliases ? 'तूअल दाल';
  update shop_products set aliases = aliases || jsonb_build_array('तूअल दाल'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'तूअल दाल';

  -- Parle-G 10: RT01/RT05/RT07/RT08/RT11/RT26: the word boundary moves, no fold reaches it
  select array_agg(id) into v_ids from base_products where display_name = 'Parle-G 10';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Parle-G 10', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases || jsonb_build_array('पार लेजी'::text) where id = v_ids[1] and not aliases ? 'पार लेजी';
  update shop_products set aliases = aliases || jsonb_build_array('पार लेजी'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'पार लेजी';
  update base_products set aliases = aliases || jsonb_build_array('पारलेजी'::text) where id = v_ids[1] and not aliases ? 'पारलेजी';
  update shop_products set aliases = aliases || jsonb_build_array('पारलेजी'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'पारलेजी';
  update base_products set aliases = aliases || jsonb_build_array('परलेजी'::text) where id = v_ids[1] and not aliases ? 'परलेजी';
  update shop_products set aliases = aliases || jsonb_build_array('परलेजी'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'परलेजी';
  update base_products set aliases = aliases || jsonb_build_array('पालेजी'::text) where id = v_ids[1] and not aliases ? 'पालेजी';
  update shop_products set aliases = aliases || jsonb_build_array('पालेजी'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'पालेजी';

  -- Chai Patti: RT14: one word vs चाय पत्ती - 0.74, under the one-word 0.85 bar
  select array_agg(id) into v_ids from base_products where display_name = 'Chai Patti';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Chai Patti', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases || jsonb_build_array('चायपत्ती'::text) where id = v_ids[1] and not aliases ? 'चायपत्ती';
  update shop_products set aliases = aliases || jsonb_build_array('चायपत्ती'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'चायपत्ती';

  -- Masoor Daal: RT23: Whisper's ल for र, 0.67 (ल/र not folded - too many real words differ only there)
  select array_agg(id) into v_ids from base_products where display_name = 'Masoor Daal';
  if coalesce(array_length(v_ids, 1), 0) <> 1 then
    raise exception 'KB-317 alias fix: base_products display_name % matches % rows, expected exactly 1', 'Masoor Daal', coalesce(array_length(v_ids, 1), 0);
  end if;
  update base_products set aliases = aliases || jsonb_build_array('मसूल दाल'::text) where id = v_ids[1] and not aliases ? 'मसूल दाल';
  update shop_products set aliases = aliases || jsonb_build_array('मसूल दाल'::text), updated_at = now() where base_product_id = v_ids[1] and source = 'base' and not aliases ? 'मसूल दाल';
end
$$;
